import { addDays, addYears } from 'date-fns'

export const data = [
  {
    key: '1',
    name: 'John Brown',
    age: 32,
    birthday: new Date(),
  },
  {
    key: '2',
    name: 'Jim Green',
    age: 42,
    birthday: new Date(),
  },
  {
    key: '3',
    name: 'Joe Black',
    age: 32,
    birthday: new Date(),
  },
  {
    key: '4',
    name: 'Jim Red',
    age: 32,
    birthday: new Date(),
  },
  {
    key: '5',
    name: 'John Brown',
    age: 32,
    birthday: new Date(),
  },
  {
    key: '6',
    name: 'Jim Green',
    age: 42,
    birthday: new Date(),
  },
  {
    key: '7',
    name: 'Joe Black',
    age: 32,
    birthday: new Date(),
  },
  {
    key: '8',
    name: 'Jim Red',
    age: 32,
    birthday: new Date(),
  },
  {
    key: '9',
    name: 'John Brown',
    age: 32,
    birthday: new Date(),
  },
  {
    key: '10',
    name: 'Jim Green',
    age: 42,
    birthday: new Date(),
  },
  {
    key: '11',
    name: 'Joe Black',
    age: 32,
    birthday: new Date(),
  },
  {
    key: '12',
    name: 'Jim Red',
    age: 32,
    birthday: new Date(),
  },
  {
    key: '13',
    name: 'John Brown',
    age: 32,
    birthday: new Date(),
  },
  {
    key: '14',
    name: 'Jim Green',
    age: 42,
    birthday: new Date(),
  },
  {
    key: '15',
    name: 'Joe Black',
    age: 32,
    birthday: new Date(),
  },
  {
    key: '16',
    name: 'Jim Red',
    age: 32,
    birthday: new Date(),
  },
  {
    key: '17',
    name: 'John Brown',
    age: 32,
    birthday: new Date(),
  },
  {
    key: '18',
    name: 'Jim Green',
    age: 42,
    birthday: new Date(),
  },
  {
    key: '19',
    name: 'Joe Black',
    age: 32,
    birthday: new Date(),
  },
  {
    key: '20',
    name: 'Jim Red',
    age: 32,
    birthday: new Date(),
  },
  {
    key: '21',
    name: 'John Brown',
    age: 32,
    birthday: new Date(),
  },
  {
    key: '22',
    name: 'Jim Green',
    age: 42,
    birthday: new Date(),
  },
  {
    key: '23',
    name: 'Joe Black',
    age: 32,
    birthday: new Date(),
  },
  {
    key: '24',
    name: 'Jim Red',
    age: 32,
    birthday: new Date(),
  },
  {
    key: '25',
    name: 'John Brown',
    age: 32,
    birthday: new Date(),
  },
  {
    key: '26',
    name: 'Jim Green',
    age: 42,
    birthday: new Date(),
  },
  {
    key: '27',
    name: 'Joe Black',
    age: 32,
    birthday: new Date(),
  },
  {
    key: '28',
    name: 'Jim Red',
    age: 32,
    birthday: new Date(),
  },
  {
    key: '29',
    name: 'John Brown',
    age: 32,
    birthday: new Date(),
  },
  {
    key: '30',
    name: 'Jim Green',
    age: 42,
    birthday: new Date(),
  },
  {
    key: '31',
    name: 'Joe Black',
    age: 32,
    birthday: new Date(),
  },
  {
    key: '32',
    name: 'Jim Red',
    age: 32,
    birthday: new Date(),
  },
  {
    key: '33',
    name: 'John Brown',
    age: 32,
    birthday: new Date(),
  },
  {
    key: '34',
    name: 'Jim Green',
    age: 42,
    birthday: new Date(),
  },
  {
    key: '35',
    name: 'Joe Black',
    age: 32,
    birthday: new Date(),
  },
  {
    key: '36',
    name: 'Jim Red',
    age: 32,
    birthday: new Date(),
  },
  {
    key: '37',
    name: 'John Brown',
    age: 32,
    birthday: new Date(),
  },
  {
    key: '38',
    name: 'Jim Green',
    age: 42,
    birthday: new Date(),
  },
  {
    key: '39',
    name: 'Joe Black',
    age: 32,
    birthday: new Date(),
  },
  {
    key: '40',
    name: 'Jim Red',
    age: 32,
    birthday: new Date(),
  },
].map((item, index) => ({
  ...item,
  birthday: addYears(addDays(item.birthday, index * 3), index),
}))
